version: '3.1'
services:
  db:
    image: postgres:12-alpine
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - db_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=!QAZcde30
      - POSTGRES_USER=olgastash
      - POSTGRES_DB=db
volumes:
  db_volume:
    external: true